# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  pathtosolution: 'EMS/'
  pathtoproject: 'EMS/EMS_Web'
  pathtotest: 'EMS/Test'
  buildConfiguration: 'Release'

steps:
# 1- script : echo First step !

#3 Sonar cloud 
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'emsproj'
    organization: 'self-upgrade-pkaur'
    scannerMode: 'MSBuild'
    projectKey: 'self-upgrade-pkaur_EMSproj'
    projectName: 'EMS proj'
    extraProperties: |
      sonar.cs.opencover.reportPaths="$(Build.ArtifactStagingDirectory)/coverage/*"
      sonar.cs.vstest.reportPaths="$(Build.ArtifactStagingDirectory)/test/*.trx"

# 2 dotnet build
- script: 
    dotnet build --configuration $(buildConfiguration)
  workingDirectory: $(pathtosolution)
  displayName: 'dotnet build $(buildConfiguration)'

# 4 Test with code MS build coverage
- script: dotnet test
    --configuration $(buildConfiguration)
    --logger trx
    --no-build
    --results-directory $(Build.ArtifactStagingDirectory)/test/
    /p:CollectCoverage=true
    /p:CoverletOutputFormat=opencover
    /p:CoverletOutput="$(Build.ArtifactStagingDirectory)/coverage/"
  workingDirectory: $(pathtosolution)  
  displayName: 'dotnet test'

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'